# Generated by Django 5.0.8 on 2024-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_route',
            field=models.FileField(blank=True, max_length=128, upload_to='file_path'),
        ),
    ]
