# Generated by Django 5.0.8 on 2024-11-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_file_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(verbose_name='Nombre del archivo'),
        ),
    ]
