# Generated by Django 5.0.8 on 2024-11-18 16:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_route',
            field=models.FileField(max_length=128, upload_to='file_path', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx', 'csv'])]),
        ),
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_document', models.PositiveSmallIntegerField(choices=[(1, 'PENDIENTE')], default=1, verbose_name='Tipo de documento')),
                ('number_document', models.CharField(verbose_name='Número de documento')),
                ('social_reason', models.CharField(verbose_name='Número de documento')),
                ('surnames', models.CharField(blank=True, verbose_name='Número de documento')),
                ('address', models.CharField(blank=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('department', models.CharField(blank=True, verbose_name='Departamento')),
                ('municipality', models.CharField(blank=True, verbose_name='Municipio')),
                ('country', models.CharField(blank=True, verbose_name='País')),
                ('phone', models.CharField(blank=True, verbose_name='Teléfono')),
                ('cell_phone', models.CharField(blank=True, verbose_name='Celular')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
