# Generated by Django 5.0.8 on 2024-11-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_file_name'),
    ]

    operations = [
    ]
