# Generated by Django 5.0.8 on 2024-11-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_filedetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetail',
            name='compound_address',
            field=models.CharField(blank=True, verbose_name='Dirección compuesta'),
        ),
        migrations.AddField(
            model_name='filedetail',
            name='notification_address',
            field=models.CharField(blank=True, verbose_name='Dirección de notificación'),
        ),
    ]
