# Generated by Django 5.0.8 on 2024-11-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241118_1420'),
        ('core', '0006_filedetail_compound_address_and_more'),
    ]

    operations = [
    ]
