# Generated by Django 5.0.8 on 2024-11-19 16:17

from django.db import migrations

from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20241119_1617'),
    ]

    operations = [
        UnaccentExtension()
    ]
