# Generated by Django 5.0.8 on 2024-11-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20241119_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'APC')], default=1, verbose_name='Tipo'),
        ),
    ]
