# Generated by Django 5.0.8 on 2024-11-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha del archivo'),
        ),
    ]
