# Generated by Django 5.0.8 on 2025-01-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='versioning',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.versioning'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='versioning',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del cargue'),
        ),
    ]
