# Generated by Django 5.0.8 on 2025-01-08 17:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_file_versioning_alter_versioning_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_excel', models.FileField(max_length=200, upload_to='reports')),
                ('file_pdf', models.FileField(max_length=200, upload_to='reports')),
                ('document', models.CharField(null=True, verbose_name='Número de documento')),
                ('versioning', models.CharField(null=True, verbose_name='Tipo de cargue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='versioning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='core.versioning'),
        ),
    ]
