# Generated by Django 5.0.8 on 2025-01-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_report_status_alter_report_file_excel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='number_records',
            field=models.IntegerField(null=True, verbose_name='Número de registros del archivo'),
        ),
    ]
