# Generated by Django 5.0.8 on 2025-01-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_report_number_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='versioning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='core.versioning', verbose_name='Tipo de cargue'),
        ),
    ]
