# Generated by Django 5.0.8 on 2025-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_report_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.IntegerField(null=True, verbose_name='Número de direcciones encontrados'),
        ),
        migrations.AddField(
            model_name='report',
            name='cell_phone',
            field=models.IntegerField(null=True, verbose_name='Número de teléfonos encontrados'),
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.IntegerField(null=True, verbose_name='Número de correos encontrados'),
        ),
        migrations.AddField(
            model_name='report',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Número de teléfonos encontrados'),
        ),
    ]
