# Generated by Django 5.0.8 on 2025-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_report_address_report_cell_phone_report_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioning',
            name='close',
            field=models.BooleanField(default=1, verbose_name='Cerrar cargue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='type_document',
            field=models.PositiveSmallIntegerField(choices=[(1, '--')], default=1, verbose_name='Tipo de documento'),
        ),
    ]
