# Generated by Django 5.0.8 on 2025-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_versioning_close_alter_filedetail_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='columns',
            field=models.CharField(null=True, verbose_name='Columnas'),
        ),
        migrations.AddField(
            model_name='report',
            name='grouped',
            field=models.CharField(null=True, verbose_name='Registro agrupado'),
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='social_reason',
            field=models.CharField(verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='surnames',
            field=models.CharField(blank=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='versioning',
            name='close',
            field=models.BooleanField(default=False, verbose_name='Cerrar cargue'),
        ),
    ]
